mixed-port: 7890
ipv6: false
allow-lan: true
mode: rule
log-level: silent
geo-auto-update: true
geo-update-interval: 168
enable-process: true
find-process-mode: strict
tcp-concurrent: true
profile:
  store-selected: true
  store-fake-ip: true
sniffer:
  enable: true
  parse-pure-ip: true
  force-dns-mapping: true
  override-destination: false
dns:
  enable: true
  listen: 0.0.0.0:1053
  ipv6: false
  respect-rules: true
  use-system-hosts: false
  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.1/16
  fake-ip-filter-mode: blacklist
  fake-ip-filter:
  - rule-set:private
  default-nameserver:
  - 8.8.8.8
  - 8.8.4.4
  nameserver:
  - 4.2.2.4
  - 1.1.1.1
  direct-nameserver:
  - 8.8.8.8
  - 8.8.4.4
  proxy-server-nameserver:
  - 4.2.2.4
  - 1.1.1.1
  fallback:
  - quic://8.8.8.8
  - quic://8.8.4.4
  - https://google.com/dns-query
  - https://8.8.8.8/dns-query
  fallback-filter:
    ipcidr:
    - 10.10.34.34/29
tun:
  enable: true
  stack: gvisor
  auto-route: true
  auto-redirect: true
  strict-route: true
  dns-hijack:
  - any:53
  - tcp://any:53
proxies:
- name: ðŸ‡¨ðŸ‡¦ VLESS 01
  type: vless
  server: am288.amin-1.ir
  port: 2082
  uuid: 3b0c38e2-0bfd-44ce-9e91-89d996202d5d
  udp: true
  tls: false
  skip-cert-verify: true
  servername: am288.amin-1.ir
  network: tcp
- name: ðŸ‡®ðŸ‡¹ VLESS 02
  type: vless
  server: 95.141.37.73
  port: 443
  uuid: 1820765e-c193-4ae1-a96c-f2c476becb4b
  udp: true
  tls: true
  skip-cert-verify: true
  servername: aws.com
  network: tcp
  client-fingerprint: chrome
  flow: xtls-rprx-vision
  reality-opts:
    public-key: ckRcueERkPqqjZABwxqni_J_Nbb70Q6k5fEEUAjoImw
- name: ðŸ‡¬ðŸ‡§ VLESS 03
  type: vless
  server: 45.140.167.209
  port: 8880
  uuid: df0680ca-e43c-498d-ed86-8e196eedd012
  udp: true
  tls: false
  skip-cert-verify: true
  servername: 45.140.167.209
  network: grpc
  grpc-opts: {}
- name: ðŸ‡³ðŸ‡± VLESS 04
  type: vless
  server: 166.1.131.6
  port: 443
  uuid: 40730d97-ffa7-1108-2c53-761516eb5fda
  udp: true
  tls: true
  skip-cert-verify: true
  servername: speed.cloudflare.com
  network: tcp
  client-fingerprint: chrome
  flow: xtls-rprx-vision
  reality-opts:
    public-key: _KiM4lu8Em0mJFmY8t2XRYGL-H2jbCtfKaFB0Io6JCE
- name: ðŸ‡©ðŸ‡ª VLESS 05
  type: vless
  server: refreshcloud-ger.parsgit.com
  port: 4040
  uuid: ba29c23c-2174-46c2-9c99-65cacc2237df
  udp: true
  tls: false
  skip-cert-verify: true
  servername: refreshcloud-ger.parsgit.com
  network: ws
  ws-opts:
    path: /admin?ed=1024--skypro_vpn--skypro_vpn--skypro_vpn--skypro_vpn--skypro_vpn--skypro_vpn--skypro_vpn--skypro_vpn--
    headers:
      Host: refreshcloud-ger.parsgit.com.
- name: ðŸ‡¦ðŸ‡ª VLESS 07
  type: vless
  server: 45.88.13.10
  port: 443
  uuid: 40730d97-ffa7-1108-2c53-761516eb5fda
  udp: true
  tls: true
  skip-cert-verify: true
  servername: speed.cloudflare.com
  network: tcp
  client-fingerprint: chrome
  flow: xtls-rprx-vision
  reality-opts:
    public-key: Tv-cNH4ADnhrcIc_JIHdTCz2PJ3b4jkmLNAJ4OVKuzY
- name: ðŸ‡«ðŸ‡® VLESS 08
  type: vless
  server: 65.109.216.23
  port: 15355
  uuid: 1a0e38e2-6276-4c36-bc00-7d2ccd6aea4d
  udp: true
  tls: false
  skip-cert-verify: true
  servername: 65.109.216.23
  network: ws
  ws-opts:
    path: /@armanstore2-Telegram----@armanstore2-Telegram----@armanstore2-Telegram----@armanstore2-Telegram----@armanstore2-Telegram----@armanstore2-Telegram----@armanstore2-Telegram----
- name: ðŸ‡ºðŸ‡¸ VLESS 09
  type: vless
  server: 185.236.232.118
  port: 80
  uuid: 401374e6-df77-41fb-f638-dad8184f175b
  udp: true
  tls: false
  skip-cert-verify: true
  servername: 185.236.232.118
  network: grpc
  grpc-opts: {}
- name: ðŸ‡«ðŸ‡· VLESS 10
  type: vless
  server: 185.231.205.176
  port: 8880
  uuid: df0680ca-e43c-498d-ed86-8e196eedd012
  udp: true
  tls: false
  skip-cert-verify: true
  servername: 185.231.205.176
  network: grpc
  grpc-opts: {}
- name: ðŸ‡ºðŸ‡¸ VLESS 11
  type: vless
  server: 185.236.232.159
  port: 80
  uuid: 401374e6-df77-41fb-f638-dad8184f175b
  udp: true
  tls: false
  skip-cert-verify: true
  servername: 185.236.232.159
  network: grpc
  grpc-opts: {}
- name: ðŸ‡©ðŸ‡ª VLESS 12
  type: vless
  server: 91.98.233.176
  port: 24199
  uuid: f3be6c78-46cd-4409-8ed3-8d36bef0f86c
  udp: true
  tls: false
  skip-cert-verify: true
  servername: 91.98.233.176
  network: tcp
- name: ðŸ‡«ðŸ‡® VLESS 13
  type: vless
  server: 171.22.114.244
  port: 8880
  uuid: df0680ca-e43c-498d-ed86-8e196eedd012
  udp: true
  tls: false
  skip-cert-verify: true
  servername: 171.22.114.244
  network: grpc
  grpc-opts: {}
- name: ðŸ‡«ðŸ‡· VLESS 15
  type: vless
  server: 94.131.118.25
  port: 8880
  uuid: df0680ca-e43c-498d-ed86-8e196eedd012
  udp: true
  tls: false
  skip-cert-verify: true
  servername: 94.131.118.25
  network: grpc
  grpc-opts: {}
- name: ðŸ‡®ðŸ‡¸ VLESS 16
  type: vless
  server: 89.221.224.216
  port: 8880
  uuid: df0680ca-e43c-498d-ed86-8e196eedd012
  udp: true
  tls: false
  skip-cert-verify: true
  servername: 89.221.224.216
  network: grpc
  grpc-opts: {}
- name: ðŸ‡¬ðŸ‡§ VLESS 17
  type: vless
  server: 94.131.122.221
  port: 8880
  uuid: df0680ca-e43c-498d-ed86-8e196eedd012
  udp: true
  tls: false
  skip-cert-verify: true
  servername: 94.131.122.221
  network: grpc
  grpc-opts: {}
- name: ðŸ‡«ðŸ‡® VLESS 18
  type: vless
  server: 171.22.114.194
  port: 8880
  uuid: df0680ca-e43c-498d-ed86-8e196eedd012
  udp: true
  tls: false
  skip-cert-verify: true
  servername: 171.22.114.194
  network: grpc
  grpc-opts: {}
- name: ðŸ‡«ðŸ‡· VLESS 19
  type: vless
  server: 185.231.205.164
  port: 8880
  uuid: df0680ca-e43c-498d-ed86-8e196eedd012
  udp: true
  tls: false
  skip-cert-verify: true
  servername: 185.231.205.164
  network: grpc
  grpc-opts: {}
proxy-groups:
- name: Smart VPN
  type: select
  lazy: true
  icon: https://cdn.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/Global.png
  proxies:
  - Auto
  - Load Balancer
  - ðŸ‡¨ðŸ‡¦ VLESS 01
  - ðŸ‡®ðŸ‡¹ VLESS 02
  - ðŸ‡¬ðŸ‡§ VLESS 03
  - ðŸ‡³ðŸ‡± VLESS 04
  - ðŸ‡©ðŸ‡ª VLESS 05
  - ðŸ‡¦ðŸ‡ª VLESS 07
  - ðŸ‡«ðŸ‡® VLESS 08
  - ðŸ‡ºðŸ‡¸ VLESS 09
  - ðŸ‡«ðŸ‡· VLESS 10
  - ðŸ‡ºðŸ‡¸ VLESS 11
  - ðŸ‡©ðŸ‡ª VLESS 12
  - ðŸ‡«ðŸ‡® VLESS 13
  - ðŸ‡«ðŸ‡· VLESS 15
  - ðŸ‡®ðŸ‡¸ VLESS 16
  - ðŸ‡¬ðŸ‡§ VLESS 17
  - ðŸ‡«ðŸ‡® VLESS 18
  - ðŸ‡«ðŸ‡· VLESS 19
- name: Auto
  type: url-test
  icon: https://cdn.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/EU.png
  url: http://gstatic.com/generate_204
  lazy: true
  interval: 120
  tolerance: 200
  hidden: true
  proxies:
  - ðŸ‡¨ðŸ‡¦ VLESS 01
  - ðŸ‡®ðŸ‡¹ VLESS 02
  - ðŸ‡¬ðŸ‡§ VLESS 03
  - ðŸ‡³ðŸ‡± VLESS 04
  - ðŸ‡©ðŸ‡ª VLESS 05
  - ðŸ‡¦ðŸ‡ª VLESS 07
  - ðŸ‡«ðŸ‡® VLESS 08
  - ðŸ‡ºðŸ‡¸ VLESS 09
  - ðŸ‡«ðŸ‡· VLESS 10
  - ðŸ‡ºðŸ‡¸ VLESS 11
  - ðŸ‡©ðŸ‡ª VLESS 12
  - ðŸ‡«ðŸ‡® VLESS 13
  - ðŸ‡«ðŸ‡· VLESS 15
  - ðŸ‡®ðŸ‡¸ VLESS 16
  - ðŸ‡¬ðŸ‡§ VLESS 17
  - ðŸ‡«ðŸ‡® VLESS 18
  - ðŸ‡«ðŸ‡· VLESS 19
- name: Load Balancer
  type: load-balance
  strategy: consistent-hashing
  icon: https://cdn.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/Bypass.png
  url: http://gstatic.com/generate_204
  lazy: true
  interval: 120
  tolerance: 200
  hidden: true
  proxies:
  - ðŸ‡¨ðŸ‡¦ VLESS 01
  - ðŸ‡®ðŸ‡¹ VLESS 02
  - ðŸ‡¬ðŸ‡§ VLESS 03
  - ðŸ‡³ðŸ‡± VLESS 04
  - ðŸ‡©ðŸ‡ª VLESS 05
  - ðŸ‡¦ðŸ‡ª VLESS 07
  - ðŸ‡«ðŸ‡® VLESS 08
  - ðŸ‡ºðŸ‡¸ VLESS 09
  - ðŸ‡«ðŸ‡· VLESS 10
  - ðŸ‡ºðŸ‡¸ VLESS 11
  - ðŸ‡©ðŸ‡ª VLESS 12
  - ðŸ‡«ðŸ‡® VLESS 13
  - ðŸ‡«ðŸ‡· VLESS 15
  - ðŸ‡®ðŸ‡¸ VLESS 16
  - ðŸ‡¬ðŸ‡§ VLESS 17
  - ðŸ‡«ðŸ‡® VLESS 18
  - ðŸ‡«ðŸ‡· VLESS 19
rule-providers:
  private:
    type: http
    format: text
    behavior: ipcidr
    url: https://github.com/Chocolate4U/Iran-clash-rules/releases/latest/download/private.txt
    path: ./ruleset/private.txt
    interval: 86400
  ircidr:
    type: http
    format: text
    behavior: ipcidr
    url: https://github.com/Chocolate4U/Iran-clash-rules/releases/latest/download/ircidr.txt
    path: ./ruleset/ircidr.txt
    interval: 86400
  iran_other:
    type: http
    format: text
    behavior: domain
    url: https://github.com/bootmortis/iran-hosted-domains/releases/latest/download/clash_rules_other.txt
    path: ./ruleset/iran_other.txt
    interval: 86400
  apps:
    type: http
    format: text
    behavior: classical
    url: https://github.com/Chocolate4U/Iran-clash-rules/releases/latest/download/apps.txt
    path: ./ruleset/apps.txt
    interval: 86400
  Pro:
    type: http
    format: text
    behavior: domain
    url: https://github.com/Chocolate4U/Iran-clash-rules/releases/latest/download/nsfw.txt
    path: ./ruleset/pro.txt
    interval: 86400
  ads:
    type: http
    format: text
    behavior: domain
    url: https://github.com/Chocolate4U/Iran-clash-rules/releases/latest/download/category-ads-all.txt
    path: ./ruleset/ads.txt
    interval: 86400
  malware:
    type: http
    format: text
    behavior: domain
    url: https://github.com/Chocolate4U/Iran-clash-rules/releases/latest/download/malware.txt
    path: ./ruleset/malware.txt
    interval: 86400
  phishing:
    type: http
    format: text
    behavior: domain
    url: https://github.com/Chocolate4U/Iran-clash-rules/releases/latest/download/phishing.txt
    path: ./ruleset/phishing.txt
    interval: 86400
  cryptominers:
    type: http
    format: text
    behavior: domain
    url: https://github.com/Chocolate4U/Iran-clash-rules/releases/latest/download/cryptominers.txt
    path: ./ruleset/cryptominers.txt
    interval: 86400
  malware-ip:
    type: http
    format: text
    behavior: ipcidr
    url: https://github.com/Chocolate4U/Iran-clash-rules/releases/latest/download/malware-ip.txt
    path: ./ruleset/malware-ip.txt
    interval: 86400
  phishing-ip:
    type: http
    format: text
    behavior: ipcidr
    url: https://github.com/Chocolate4U/Iran-clash-rules/releases/latest/download/phishing-ip.txt
    path: ./ruleset/phishing-ip.txt
    interval: 86400
rules:
- DOMAIN-SUFFIX,ir,DIRECT
- DOMAIN-SUFFIX,.ir,DIRECT
- DOMAIN,www.cloudflare.com,DIRECT
- RULE-SET,ads,REJECT
- RULE-SET,malware,REJECT
- RULE-SET,malware-ip,REJECT
- RULE-SET,phishing,REJECT
- RULE-SET,phishing-ip,REJECT
- RULE-SET,cryptominers,REJECT
- RULE-SET,private,DIRECT
- RULE-SET,ircidr,DIRECT
- RULE-SET,iran_other,DIRECT
- RULE-SET,apps,DIRECT
- MATCH,Smart VPN
ntp:
  enable: true
  server: time.apple.com
  port: 123
  interval: 30
