mixed-port: 7890
ipv6: false
allow-lan: true
mode: rule
log-level: silent
geo-auto-update: true
geo-update-interval: 168
enable-process: true
find-process-mode: strict
tcp-concurrent: true
profile:
  store-selected: true
  store-fake-ip: true
sniffer:
  enable: true
  parse-pure-ip: true
  force-dns-mapping: true
  override-destination: false
dns:
  enable: true
  listen: 0.0.0.0:1053
  ipv6: false
  respect-rules: true
  use-system-hosts: false
  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.1/16
  fake-ip-filter-mode: blacklist
  fake-ip-filter:
  - rule-set:private
  default-nameserver:
  - 8.8.8.8
  - 8.8.4.4
  nameserver:
  - 4.2.2.4
  - 1.1.1.1
  direct-nameserver:
  - 8.8.8.8
  - 8.8.4.4
  proxy-server-nameserver:
  - 4.2.2.4
  - 1.1.1.1
  fallback:
  - quic://8.8.8.8
  - quic://8.8.4.4
  - https://google.com/dns-query
  - https://8.8.8.8/dns-query
  fallback-filter:
    ipcidr:
    - 10.10.34.34/29
tun:
  enable: true
  stack: gvisor
  auto-route: true
  auto-redirect: true
  strict-route: true
  dns-hijack:
  - any:53
  - tcp://any:53
proxies:
- name: ðŸ‡°ðŸ‡· VMESS 01
  type: vmess
  server: seoul03.zgjok.com
  port: 443
  uuid: 72a0dac4-9689-4a57-b164-5c65bfa94772
  alterId: 0
  udp: true
  skip-cert-verify: true
  cipher: auto
  network: ws
  tls: true
  servername: seoul03.zgjok.com
  ws-opts:
    path: /
    headers:
      Host: seoul03.zgjok.com
- name: ðŸ‡¯ðŸ‡µ TROJAN 02
  type: trojan
  server: 160.16.106.144
  port: 4054
  password: 76d630f2af6619c4a5de0ef953df3c6a
  udp: true
  skip-cert-verify: true
  sni: www.nintendogames.net
- name: ðŸ‡¨ðŸ‡¦ VLESS 03
  type: vless
  server: brenna.ns.cloudflare.com
  port: 443
  uuid: 1b2c91ab-f6c9-42f8-b2c6-8de0ac133d63
  udp: true
  tls: true
  skip-cert-verify: true
  servername: terazhedi.info
  network: ws
  ws-opts:
    path: /sghiyws
    headers:
      Host: terazhedi.info
- name: ðŸ‡©ðŸ‡ª VLESS 04
  type: vless
  server: m95a.vip784.com
  port: 33801
  uuid: 7d3bb6bd-8122-4cce-ba4a-2f8df0bcd816
  udp: true
  tls: false
  skip-cert-verify: true
  servername: m95a.vip784.com
  network: tcp
- name: ðŸ‡·ðŸ‡º VLESS 05
  type: vless
  server: 217.16.24.170
  port: 443
  uuid: a91e64f0-9295-499d-bf4a-661ad99d4938
  udp: true
  tls: true
  skip-cert-verify: true
  servername: api-maps.yandex.ru
  network: tcp
  client-fingerprint: chrome
  flow: xtls-rprx-vision
  reality-opts:
    public-key: 8OsJx6xuHcpL_5e1w0U4bMBa-icevDgvvzNwPwZbORQ
    short-id: 5540e44a53c3d01c
- name: ðŸ‡¨ðŸ‡¦ VLESS 06
  type: vless
  server: 108.162.195.45
  port: 443
  uuid: 7270612b-49f6-4b04-999c-34d8263da767
  udp: true
  tls: true
  skip-cert-verify: true
  servername: picassoo.info
  network: ws
  client-fingerprint: chrome
  ws-opts:
    path: /aymdlws
    headers:
      Host: picassoo.info
- name: ðŸ‡¨ðŸ‡¦ VLESS 07
  type: vless
  server: 172.64.34.176
  port: 443
  uuid: 1b2c91ab-f6c9-42f8-b2c6-8de0ac133d63
  udp: true
  tls: true
  skip-cert-verify: true
  servername: terazhedi.info
  network: ws
  ws-opts:
    path: /sghiyws
    headers:
      Host: terazhedi.info
- name: ðŸ‡¨ðŸ‡¦ VLESS 08
  type: vless
  server: cosmin.ns.cloudflare.com
  port: 443
  uuid: 7270612b-49f6-4b04-999c-34d8263da767
  udp: true
  tls: true
  skip-cert-verify: true
  servername: picassoo.info
  network: ws
  ws-opts:
    path: /aymdlws
    headers:
      Host: picassoo.info
- name: ðŸ‡©ðŸ‡ª VMESS 09
  type: vmess
  server: 129.212.194.164
  port: 7443
  uuid: 5c6d4107-464b-40f1-b356-de21ed1f0ced
  alterId: 0
  udp: true
  skip-cert-verify: true
  cipher: none
  network: tcp
- name: ðŸ‡©ðŸ‡ª VMESS 10
  type: vmess
  server: a.confignor.site
  port: 7443
  uuid: 1299fd91-90b5-41b7-b820-556f33deab0b
  alterId: 0
  udp: true
  skip-cert-verify: true
  cipher: none
  network: tcp
- name: ðŸ‡«ðŸ‡® VLESS 15
  type: vless
  server: helsinki.fonixapp.org
  port: 2083
  uuid: 2825bed8-db26-4722-81db-0f572f19dac5
  udp: true
  tls: true
  skip-cert-verify: true
  servername: clients4.google.com
  network: tcp
  client-fingerprint: chrome
  flow: xtls-rprx-vision
  reality-opts:
    public-key: 0ynmhxgUxTCCEhdgYsH1-_90sX5jztkAwUrarbruPS8
    short-id: 8c
- name: ðŸ‡ºðŸ‡¸ VLESS 16
  type: vless
  server: deu711.deulucker.org
  port: 444
  uuid: 33676069-bc5a-443c-bb64-14a215544f2b
  udp: true
  tls: true
  skip-cert-verify: true
  servername: deu711.deulucker.org
  network: tcp
  client-fingerprint: chrome
  reality-opts:
    public-key: BhTJ3phnq-Z-10aFKSsj1lzhA8mULR4L6leE4-0WTAs
- name: ðŸ‡·ðŸ‡º VLESS 17
  type: vless
  server: us01-vlr01-gmn03.vpnvezdehod.net
  port: 443
  uuid: 2ca07504-c06a-41a4-b26b-99807a7d24cf
  udp: true
  tls: true
  skip-cert-verify: true
  servername: hls-svod.itunes.apple.com
  network: tcp
  client-fingerprint: chrome
  flow: xtls-rprx-vision
  reality-opts:
    public-key: mLmBhbVFfNuo2eUgBh6r9-5Koz9mUCn3aSzlR6IejUg
    short-id: 48720c
- name: ðŸ‡·ðŸ‡º VLESS 18
  type: vless
  server: 51.250.24.245
  port: 4249
  uuid: 4a6de183-2ad3-456c-b420-feeac81f6257
  udp: true
  tls: true
  skip-cert-verify: true
  servername: api-maps.yandex.ru
  network: tcp
  client-fingerprint: chrome
  flow: xtls-rprx-vision
  reality-opts:
    public-key: SbVKOEMjK0sIlbwg4akyBg5mL5KZwwB-ed4eEE7YnRc
    short-id: 6ba85179e30d4fc2
- name: ðŸ‡¨ðŸ‡¦ VLESS 19
  type: vless
  server: clyde.ns.cloudflare.com
  port: 443
  uuid: 02e46039-200d-4ae4-ac90-b0d619f72034
  udp: true
  tls: true
  skip-cert-verify: true
  servername: redlabell.info
  network: ws
  ws-opts:
    path: /aafeuws
    headers:
      Host: redlabell.info
- name: ðŸ‡·ðŸ‡º VLESS 20
  type: vless
  server: 185.234.59.74
  port: 8443
  uuid: 2ca07504-c06a-41a4-b26b-99807a7d24cf
  udp: true
  tls: true
  skip-cert-verify: true
  servername: stats.vk-portal.net
  network: tcp
  client-fingerprint: chrome
  flow: xtls-rprx-vision
  reality-opts:
    public-key: mLmBhbVFfNuo2eUgBh6r9-5Koz9mUCn3aSzlR6IejUg
    short-id: e499f276e7bd6420
- name: ðŸ‡«ðŸ‡® VLESS 21
  type: vless
  server: m59a.vip784.com
  port: 33801
  uuid: f8a88a3f-1cca-4f93-ad79-4ccc1714c1c2
  udp: true
  tls: false
  skip-cert-verify: true
  servername: m59a.vip784.com
  network: tcp
proxy-groups:
- name: Smart VPN
  type: select
  lazy: true
  icon: https://cdn.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/Global.png
  proxies:
  - Auto
  - Load Balancer
  - ðŸ‡°ðŸ‡· VMESS 01
  - ðŸ‡¯ðŸ‡µ TROJAN 02
  - ðŸ‡¨ðŸ‡¦ VLESS 03
  - ðŸ‡©ðŸ‡ª VLESS 04
  - ðŸ‡·ðŸ‡º VLESS 05
  - ðŸ‡¨ðŸ‡¦ VLESS 06
  - ðŸ‡¨ðŸ‡¦ VLESS 07
  - ðŸ‡¨ðŸ‡¦ VLESS 08
  - ðŸ‡©ðŸ‡ª VMESS 09
  - ðŸ‡©ðŸ‡ª VMESS 10
  - ðŸ‡«ðŸ‡® VLESS 15
  - ðŸ‡ºðŸ‡¸ VLESS 16
  - ðŸ‡·ðŸ‡º VLESS 17
  - ðŸ‡·ðŸ‡º VLESS 18
  - ðŸ‡¨ðŸ‡¦ VLESS 19
  - ðŸ‡·ðŸ‡º VLESS 20
  - ðŸ‡«ðŸ‡® VLESS 21
- name: Auto
  type: url-test
  icon: https://cdn.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/EU.png
  url: http://gstatic.com/generate_204
  lazy: true
  interval: 120
  tolerance: 200
  hidden: true
  proxies:
  - ðŸ‡°ðŸ‡· VMESS 01
  - ðŸ‡¯ðŸ‡µ TROJAN 02
  - ðŸ‡¨ðŸ‡¦ VLESS 03
  - ðŸ‡©ðŸ‡ª VLESS 04
  - ðŸ‡·ðŸ‡º VLESS 05
  - ðŸ‡¨ðŸ‡¦ VLESS 06
  - ðŸ‡¨ðŸ‡¦ VLESS 07
  - ðŸ‡¨ðŸ‡¦ VLESS 08
  - ðŸ‡©ðŸ‡ª VMESS 09
  - ðŸ‡©ðŸ‡ª VMESS 10
  - ðŸ‡«ðŸ‡® VLESS 15
  - ðŸ‡ºðŸ‡¸ VLESS 16
  - ðŸ‡·ðŸ‡º VLESS 17
  - ðŸ‡·ðŸ‡º VLESS 18
  - ðŸ‡¨ðŸ‡¦ VLESS 19
  - ðŸ‡·ðŸ‡º VLESS 20
  - ðŸ‡«ðŸ‡® VLESS 21
- name: Load Balancer
  type: load-balance
  strategy: consistent-hashing
  icon: https://cdn.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/Bypass.png
  url: http://gstatic.com/generate_204
  lazy: true
  interval: 120
  tolerance: 200
  hidden: true
  proxies:
  - ðŸ‡°ðŸ‡· VMESS 01
  - ðŸ‡¯ðŸ‡µ TROJAN 02
  - ðŸ‡¨ðŸ‡¦ VLESS 03
  - ðŸ‡©ðŸ‡ª VLESS 04
  - ðŸ‡·ðŸ‡º VLESS 05
  - ðŸ‡¨ðŸ‡¦ VLESS 06
  - ðŸ‡¨ðŸ‡¦ VLESS 07
  - ðŸ‡¨ðŸ‡¦ VLESS 08
  - ðŸ‡©ðŸ‡ª VMESS 09
  - ðŸ‡©ðŸ‡ª VMESS 10
  - ðŸ‡«ðŸ‡® VLESS 15
  - ðŸ‡ºðŸ‡¸ VLESS 16
  - ðŸ‡·ðŸ‡º VLESS 17
  - ðŸ‡·ðŸ‡º VLESS 18
  - ðŸ‡¨ðŸ‡¦ VLESS 19
  - ðŸ‡·ðŸ‡º VLESS 20
  - ðŸ‡«ðŸ‡® VLESS 21
rule-providers:
  private:
    type: http
    format: text
    behavior: ipcidr
    url: https://github.com/Chocolate4U/Iran-clash-rules/releases/latest/download/private.txt
    path: ./ruleset/private.txt
    interval: 86400
  ircidr:
    type: http
    format: text
    behavior: ipcidr
    url: https://github.com/Chocolate4U/Iran-clash-rules/releases/latest/download/ircidr.txt
    path: ./ruleset/ircidr.txt
    interval: 86400
  iran_other:
    type: http
    format: text
    behavior: domain
    url: https://github.com/bootmortis/iran-hosted-domains/releases/latest/download/clash_rules_other.txt
    path: ./ruleset/iran_other.txt
    interval: 86400
  apps:
    type: http
    format: text
    behavior: classical
    url: https://github.com/Chocolate4U/Iran-clash-rules/releases/latest/download/apps.txt
    path: ./ruleset/apps.txt
    interval: 86400
  Pro:
    type: http
    format: text
    behavior: domain
    url: https://github.com/Chocolate4U/Iran-clash-rules/releases/latest/download/nsfw.txt
    path: ./ruleset/pro.txt
    interval: 86400
  ads:
    type: http
    format: text
    behavior: domain
    url: https://github.com/Chocolate4U/Iran-clash-rules/releases/latest/download/category-ads-all.txt
    path: ./ruleset/ads.txt
    interval: 86400
  malware:
    type: http
    format: text
    behavior: domain
    url: https://github.com/Chocolate4U/Iran-clash-rules/releases/latest/download/malware.txt
    path: ./ruleset/malware.txt
    interval: 86400
  phishing:
    type: http
    format: text
    behavior: domain
    url: https://github.com/Chocolate4U/Iran-clash-rules/releases/latest/download/phishing.txt
    path: ./ruleset/phishing.txt
    interval: 86400
  cryptominers:
    type: http
    format: text
    behavior: domain
    url: https://github.com/Chocolate4U/Iran-clash-rules/releases/latest/download/cryptominers.txt
    path: ./ruleset/cryptominers.txt
    interval: 86400
  malware-ip:
    type: http
    format: text
    behavior: ipcidr
    url: https://github.com/Chocolate4U/Iran-clash-rules/releases/latest/download/malware-ip.txt
    path: ./ruleset/malware-ip.txt
    interval: 86400
  phishing-ip:
    type: http
    format: text
    behavior: ipcidr
    url: https://github.com/Chocolate4U/Iran-clash-rules/releases/latest/download/phishing-ip.txt
    path: ./ruleset/phishing-ip.txt
    interval: 86400
rules:
- DOMAIN-SUFFIX,ir,DIRECT
- DOMAIN-SUFFIX,.ir,DIRECT
- DOMAIN,www.cloudflare.com,DIRECT
- RULE-SET,ads,REJECT
- RULE-SET,malware,REJECT
- RULE-SET,malware-ip,REJECT
- RULE-SET,phishing,REJECT
- RULE-SET,phishing-ip,REJECT
- RULE-SET,cryptominers,REJECT
- RULE-SET,private,DIRECT
- RULE-SET,ircidr,DIRECT
- RULE-SET,iran_other,DIRECT
- RULE-SET,apps,DIRECT
- MATCH,Smart VPN
ntp:
  enable: true
  server: time.apple.com
  port: 123
  interval: 30
