mixed-port: 7890
ipv6: false
allow-lan: true
mode: rule
log-level: silent
geo-auto-update: true
geo-update-interval: 168
enable-process: true
find-process-mode: strict
tcp-concurrent: true
profile:
  store-selected: true
  store-fake-ip: true
sniffer:
  enable: true
  parse-pure-ip: true
  force-dns-mapping: true
  override-destination: false
dns:
  enable: true
  listen: 0.0.0.0:1053
  ipv6: false
  respect-rules: true
  use-system-hosts: false
  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.1/16
  fake-ip-filter-mode: blacklist
  fake-ip-filter:
  - rule-set:private
  default-nameserver:
  - 8.8.8.8
  - 8.8.4.4
  nameserver:
  - 4.2.2.4
  - 1.1.1.1
  direct-nameserver:
  - 8.8.8.8
  - 8.8.4.4
  proxy-server-nameserver:
  - 4.2.2.4
  - 1.1.1.1
  fallback:
  - quic://8.8.8.8
  - quic://8.8.4.4
  - https://google.com/dns-query
  - https://8.8.8.8/dns-query
  fallback-filter:
    ipcidr:
    - 10.10.34.34/29
tun:
  enable: true
  stack: gvisor
  auto-route: true
  auto-redirect: true
  strict-route: true
  dns-hijack:
  - any:53
  - tcp://any:53
proxies:
- name: ğŸ‡©ğŸ‡ª VLESS 01
  type: vless
  server: 91.99.184.135
  port: 2095
  uuid: 360ab6ba-7c33-4cd7-add1-9698b9f9205c
  udp: true
  tls: false
  skip-cert-verify: true
  servername: 91.99.184.135
  network: tcp
- name: ğŸ‡ºğŸ‡¸ VMESS 02
  type: vmess
  server: www.speedtest.net
  port: 443
  uuid: 03fcc618-b93d-6796-6aed-8a38c975d581
  alterId: 0
  udp: true
  skip-cert-verify: true
  cipher: auto
  network: ws
  tls: true
  servername: mrvpn294.pocom3am.workers.dev
  ws-opts:
    path: /serkat.org/linkvws
    headers:
      Host: mrvpn294.pocom3am.workers.dev
- name: ğŸ‡«ğŸ‡· VLESS 03
  type: vless
  server: 185.234.64.143
  port: 8880
  uuid: df0680ca-e43c-498d-ed86-8e196eedd012
  udp: true
  tls: false
  skip-cert-verify: true
  servername: 185.234.64.143
  network: grpc
  grpc-opts: {}
- name: ğŸ‡ºğŸ‡¸ VLESS 04
  type: vless
  server: best.cdniran.info
  port: 443
  uuid: e999db7a-1b17-4da6-bc37-c9fa24af2e93
  udp: true
  tls: true
  skip-cert-verify: true
  servername: smart.trevanda.info
  network: ws
  alpn:
  - h3
  - h2
  client-fingerprint: chrome
  ws-opts:
    path: /?@Evay_vpn----@Evay_vpn----@Evay_vpn----@Evay_vpn----@Evay_vpn----@Evay_vpn----@Evay_vpn----@Evay_vpn----@Evay_vpn----@Evay_vpn----@Evay_vpn----@Evay_vpn----@Evay_vpn----@Evay_vpn----@Evay_vpn----@Evay_vpn----@Evay_vpn----@Evay_vpn----@Evay_vpn----@Evay_vpn----@Evay_vpn
    headers:
      Host: smart.trevanda.info
- name: ğŸ‡¹ğŸ‡· VLESS 05
  type: vless
  server: 185.234.66.106
  port: 8880
  uuid: df0680ca-e43c-498d-ed86-8e196eedd012
  udp: true
  tls: false
  skip-cert-verify: true
  servername: 185.234.66.106
  network: grpc
  grpc-opts: {}
- name: ğŸ‡¹ğŸ‡· VLESS 07
  type: vless
  server: turkey.huqpmfood.ir
  port: 1331
  uuid: 1d66467e-fd2c-4321-92cc-79465ce2c25c
  udp: true
  tls: true
  skip-cert-verify: true
  servername: stackoverflow.com
  network: tcp
  client-fingerprint: chrome
  reality-opts:
    public-key: m8Tuf48MMB9ILy--1nfwGRPJOEbgHOdylaLS_JQ66DM
    short-id: 89345bea5809f46d
- name: ğŸ‡«ğŸ‡· VLESS 08
  type: vless
  server: 195.42.233.89
  port: 8880
  uuid: df0680ca-e43c-498d-ed86-8e196eedd012
  udp: true
  tls: false
  skip-cert-verify: true
  servername: 195.42.233.89
  network: grpc
  grpc-opts: {}
- name: ğŸ‡«ğŸ‡· VLESS 09
  type: vless
  server: 185.231.205.149
  port: 8880
  uuid: df0680ca-e43c-498d-ed86-8e196eedd012
  udp: true
  tls: false
  skip-cert-verify: true
  servername: 185.231.205.149
  network: grpc
  grpc-opts: {}
- name: ğŸ‡©ğŸ‡ª VLESS 10
  type: vless
  server: 193.24.209.127
  port: 36898
  uuid: 7453db5a-ca2c-4d60-a106-1a6618fd856d
  udp: true
  tls: false
  skip-cert-verify: true
  servername: 193.24.209.127
  network: tcp
- name: ğŸ‡¬ğŸ‡§ VLESS 12
  type: vless
  server: 91.228.10.89
  port: 8880
  uuid: df0680ca-e43c-498d-ed86-8e196eedd012
  udp: true
  tls: false
  skip-cert-verify: true
  servername: 91.228.10.89
  network: grpc
  grpc-opts: {}
- name: ğŸ‡³ğŸ‡± VLESS 13
  type: vless
  server: 77.91.123.207
  port: 8880
  uuid: df0680ca-e43c-498d-ed86-8e196eedd012
  udp: true
  tls: false
  skip-cert-verify: true
  servername: 77.91.123.207
  network: grpc
  grpc-opts: {}
- name: ğŸ‡©ğŸ‡ª VLESS 14
  type: vless
  server: 142.93.168.131
  port: 443
  uuid: 7c4d2229-fa3a-4628-8abf-0728f13edac1
  udp: true
  tls: false
  skip-cert-verify: true
  servername: 142.93.168.131
  network: grpc
  grpc-opts: {}
- name: ğŸ‡©ğŸ‡ª VLESS 15
  type: vless
  server: a-lf-0.okamii.ir
  port: 2095
  uuid: 360ab6ba-7c33-4cd7-add1-9698b9f9205c
  udp: true
  tls: false
  skip-cert-verify: true
  servername: a-lf-0.okamii.ir
  network: tcp
- name: ğŸ‡ºğŸ‡¸ VLESS 16
  type: vless
  server: 88.218.93.159
  port: 8880
  uuid: df0680ca-e43c-498d-ed86-8e196eedd012
  udp: true
  tls: false
  skip-cert-verify: true
  servername: 88.218.93.159
  network: grpc
  grpc-opts: {}
- name: ğŸ‡«ğŸ‡· VLESS 18
  type: vless
  server: 185.234.64.101
  port: 8880
  uuid: df0680ca-e43c-498d-ed86-8e196eedd012
  udp: true
  tls: false
  skip-cert-verify: true
  servername: 185.234.64.101
  network: grpc
  grpc-opts: {}
- name: ğŸ‡³ğŸ‡± VLESS 19
  type: vless
  server: 45.12.142.96
  port: 8880
  uuid: df0680ca-e43c-498d-ed86-8e196eedd012
  udp: true
  tls: false
  skip-cert-verify: true
  servername: 45.12.142.96
  network: grpc
  grpc-opts: {}
- name: ğŸ‡³ğŸ‡± VLESS 20
  type: vless
  server: 45.14.244.44
  port: 8880
  uuid: df0680ca-e43c-498d-ed86-8e196eedd012
  udp: true
  tls: false
  skip-cert-verify: true
  servername: 45.14.244.44
  network: grpc
  grpc-opts: {}
- name: ğŸ‡µğŸ‡± VLESS 21
  type: vless
  server: 77.83.246.235
  port: 443
  uuid: 37e7881f-ff59-4858-83cd-c6b4b03cba4a
  udp: true
  tls: true
  skip-cert-verify: true
  servername: google.com
  network: tcp
  client-fingerprint: chrome
  flow: xtls-rprx-vision
  reality-opts:
    public-key: 8B1aKLm3jBQ_yf3aUvdagWwxkXHrlRyrzdQVoq17yXI
    short-id: 698295d180
- name: ğŸ‡«ğŸ‡· VLESS 22
  type: vless
  server: 194.4.49.219
  port: 8880
  uuid: df0680ca-e43c-498d-ed86-8e196eedd012
  udp: true
  tls: false
  skip-cert-verify: true
  servername: 194.4.49.219
  network: grpc
  grpc-opts: {}
- name: ğŸ‡ªğŸ‡¸ VLESS 24
  type: vless
  server: 45.12.150.97
  port: 8880
  uuid: df0680ca-e43c-498d-ed86-8e196eedd012
  udp: true
  tls: false
  skip-cert-verify: true
  servername: 45.12.150.97
  network: grpc
  grpc-opts: {}
- name: ğŸ‡³ğŸ‡± VLESS 25
  type: vless
  server: 85.208.110.217
  port: 8880
  uuid: df0680ca-e43c-498d-ed86-8e196eedd012
  udp: true
  tls: false
  skip-cert-verify: true
  servername: 85.208.110.217
  network: grpc
  grpc-opts: {}
- name: ğŸ‡¸ğŸ‡ª VLESS 26
  type: vless
  server: 185.36.145.171
  port: 3030
  uuid: 0027ba99-cffd-477f-915f-9a80ecc857ae
  udp: true
  tls: false
  skip-cert-verify: true
  servername: 185.36.145.171
  network: tcp
- name: ğŸ‡³ğŸ‡± VLESS 28
  type: vless
  server: 193.227.99.113
  port: 2053
  uuid: 08cb0591-5193-4a0c-9105-ceb09fba67fe
  udp: true
  tls: true
  skip-cert-verify: true
  servername: nkGgd-87836.phoenixappdatad.uk
  network: ws
  alpn:
  - h3
  - h2
  - http/1.1
  client-fingerprint: chrome
  ws-opts:
    path: /
    headers:
      Host: nkGgd-87836.phoenixappdatad.uk
- name: ğŸ‡¬ğŸ‡§ VLESS 32
  type: vless
  server: 146.19.230.247
  port: 8880
  uuid: df0680ca-e43c-498d-ed86-8e196eedd012
  udp: true
  tls: false
  skip-cert-verify: true
  servername: 146.19.230.247
  network: grpc
  grpc-opts: {}
- name: ğŸ‡ºğŸ‡¸ VLESS 33
  type: vless
  server: www.speedtest.net
  port: 2082
  uuid: 0413976d-7077-42c2-d40c-7e4c735b2095
  udp: true
  tls: false
  skip-cert-verify: true
  servername: www.speedtest.net
  network: tcp
- name: ğŸ‡±ğŸ‡¹ VLESS 35
  type: vless
  server: 94.131.14.48
  port: 8880
  uuid: df0680ca-e43c-498d-ed86-8e196eedd012
  udp: true
  tls: false
  skip-cert-verify: true
  servername: 94.131.14.48
  network: grpc
  grpc-opts: {}
- name: ğŸ‡«ğŸ‡· VLESS 36
  type: vless
  server: 194.4.49.40
  port: 8880
  uuid: df0680ca-e43c-498d-ed86-8e196eedd012
  udp: true
  tls: false
  skip-cert-verify: true
  servername: 194.4.49.40
  network: grpc
  grpc-opts: {}
- name: ğŸ‡³ğŸ‡± VLESS 38
  type: vless
  server: 85.208.110.38
  port: 8880
  uuid: df0680ca-e43c-498d-ed86-8e196eedd012
  udp: true
  tls: false
  skip-cert-verify: true
  servername: 85.208.110.38
  network: grpc
  grpc-opts: {}
- name: ğŸ‡«ğŸ‡· VLESS 39
  type: vless
  server: 185.242.87.72
  port: 8880
  uuid: df0680ca-e43c-498d-ed86-8e196eedd012
  udp: true
  tls: false
  skip-cert-verify: true
  servername: 185.242.87.72
  network: grpc
  grpc-opts: {}
- name: ğŸ‡©ğŸ‡ª VLESS 40
  type: vless
  server: v2ngnet.huqpmfood.ir
  port: 4455
  uuid: 6c95605e-b57d-402f-86ab-289fe7a73fb5
  udp: true
  tls: true
  skip-cert-verify: true
  servername: stackoverflow.com
  network: tcp
  client-fingerprint: chrome
  reality-opts:
    public-key: l_LBBQyt6du7ZgBadETGtx8zLgUd36-4mZVCSI9qqwA
    short-id: 077dc29a23d311f2
- name: ğŸ‡ºğŸ‡¸ VLESS 41
  type: vless
  server: 185.236.232.82
  port: 80
  uuid: 401374e6-df77-41fb-f638-dad8184f175b
  udp: true
  tls: false
  skip-cert-verify: true
  servername: 185.236.232.82
  network: grpc
  grpc-opts: {}
- name: ğŸ‡ºğŸ‡¸ TROJAN 42
  type: trojan
  server: 23.186.200.109
  port: 11013
  password: 898e1dca-14b2-4371-abc8-1b9f839bff6d
  udp: true
  skip-cert-verify: true
  sni: wus03.weyaf9sdoh2h.space
- name: ğŸ‡ºğŸ‡¸ VLESS 43
  type: vless
  server: 185.236.232.118
  port: 80
  uuid: 401374e6-df77-41fb-f638-dad8184f175b
  udp: true
  tls: false
  skip-cert-verify: true
  servername: 185.236.232.118
  network: grpc
  grpc-opts: {}
- name: ğŸ‡«ğŸ‡· VLESS 45
  type: vless
  server: 185.242.87.119
  port: 8880
  uuid: df0680ca-e43c-498d-ed86-8e196eedd012
  udp: true
  tls: false
  skip-cert-verify: true
  servername: 185.242.87.119
  network: grpc
  grpc-opts: {}
- name: ğŸ‡¹ğŸ‡· VLESS 46
  type: vless
  server: 185.234.66.88
  port: 8880
  uuid: df0680ca-e43c-498d-ed86-8e196eedd012
  udp: true
  tls: false
  skip-cert-verify: true
  servername: 185.234.66.88
  network: grpc
  grpc-opts: {}
- name: ğŸ‡¬ğŸ‡§ VLESS 47
  type: vless
  server: m33a.vip784.com
  port: 33801
  uuid: ad069756-c14b-4443-87af-4a503c5c08f5
  udp: true
  tls: false
  skip-cert-verify: true
  servername: m33a.vip784.com
  network: tcp
- name: ğŸ‡ºğŸ‡¸ TROJAN 48
  type: trojan
  server: 23.186.200.111
  port: 11015
  password: 898e1dca-14b2-4371-abc8-1b9f839bff6d
  udp: true
  skip-cert-verify: true
  sni: wus05.weyaf9sdoh2h.space
- name: ğŸ‡«ğŸ‡· VLESS 50
  type: vless
  server: 185.234.64.105
  port: 8880
  uuid: df0680ca-e43c-498d-ed86-8e196eedd012
  udp: true
  tls: false
  skip-cert-verify: true
  servername: 185.234.64.105
  network: grpc
  grpc-opts: {}
- name: ğŸ‡«ğŸ‡· VLESS 54
  type: vless
  server: 95.164.6.156
  port: 8880
  uuid: df0680ca-e43c-498d-ed86-8e196eedd012
  udp: true
  tls: false
  skip-cert-verify: true
  servername: 95.164.6.156
  network: grpc
  grpc-opts: {}
- name: ğŸ‡³ğŸ‡± VLESS 55
  type: vless
  server: 85.208.110.41
  port: 8880
  uuid: df0680ca-e43c-498d-ed86-8e196eedd012
  udp: true
  tls: false
  skip-cert-verify: true
  servername: 85.208.110.41
  network: grpc
  grpc-opts: {}
- name: ğŸ‡«ğŸ‡· VLESS 56
  type: vless
  server: 195.42.233.91
  port: 8880
  uuid: df0680ca-e43c-498d-ed86-8e196eedd012
  udp: true
  tls: false
  skip-cert-verify: true
  servername: 195.42.233.91
  network: grpc
  grpc-opts: {}
- name: ğŸ‡¨ğŸ‡¦ VLESS 58
  type: vless
  server: m15a.vip784.com
  port: 33801
  uuid: d36f457f-17a9-4891-a113-322ec6792917
  udp: true
  tls: false
  skip-cert-verify: true
  servername: m15a.vip784.com
  network: tcp
- name: ğŸ‡«ğŸ‡· VLESS 63
  type: vless
  server: 185.242.87.162
  port: 443
  uuid: 35b0de8b-b156-43ff-a0e6-59f1018f7adb
  udp: true
  tls: true
  skip-cert-verify: true
  servername: 185.242.87.162
  network: ws
  client-fingerprint: chrome
  ws-opts:
    path: /holhclws
- name: ğŸ‡«ğŸ‡· VLESS 64
  type: vless
  server: 86.104.74.177
  port: 8880
  uuid: df0680ca-e43c-498d-ed86-8e196eedd012
  udp: true
  tls: false
  skip-cert-verify: true
  servername: 86.104.74.177
  network: grpc
  grpc-opts: {}
- name: ğŸ‡«ğŸ‡· VLESS 65
  type: vless
  server: 185.242.87.241
  port: 8880
  uuid: df0680ca-e43c-498d-ed86-8e196eedd012
  udp: true
  tls: false
  skip-cert-verify: true
  servername: 185.242.87.241
  network: grpc
  grpc-opts: {}
- name: ğŸ‡©ğŸ‡ª VLESS 67
  type: vless
  server: 90.156.228.109
  port: 8443
  uuid: 3a4524bb-5d17-4c09-b523-6ab1e1a41d81
  udp: true
  tls: true
  skip-cert-verify: true
  servername: www.ya.ru
  network: tcp
  client-fingerprint: chrome
  flow: xtls-rprx-vision
  reality-opts:
    public-key: blSlAMMTv5UdIZiQd6VtBlS7kfZJ9xpw9H95Ouohbxs
    short-id: 4bb9dbdad476124c
- name: ğŸŒ VLESS 68
  type: vless
  server: 185.234.66.100
  port: 8880
  uuid: df0680ca-e43c-498d-ed86-8e196eedd012
  udp: true
  tls: false
  skip-cert-verify: true
  servername: 185.234.66.100
  network: grpc
  grpc-opts: {}
- name: ğŸŒ VLESS 69
  type: vless
  server: 193.233.19.242
  port: 6060
  uuid: cb6e6e21-7bc1-4de6-b961-a78893935436
  udp: true
  tls: true
  skip-cert-verify: true
  servername: book.smnsoft.com
  network: tcp
  alpn:
  - h2
  - http/1.1
  client-fingerprint: chrome
proxy-groups:
- name: Smart VPN
  type: select
  lazy: true
  icon: https://cdn.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/Global.png
  proxies:
  - Auto
  - Load Balancer
  - ğŸ‡©ğŸ‡ª VLESS 01
  - ğŸ‡ºğŸ‡¸ VMESS 02
  - ğŸ‡«ğŸ‡· VLESS 03
  - ğŸ‡ºğŸ‡¸ VLESS 04
  - ğŸ‡¹ğŸ‡· VLESS 05
  - ğŸ‡¹ğŸ‡· VLESS 07
  - ğŸ‡«ğŸ‡· VLESS 08
  - ğŸ‡«ğŸ‡· VLESS 09
  - ğŸ‡©ğŸ‡ª VLESS 10
  - ğŸ‡¬ğŸ‡§ VLESS 12
  - ğŸ‡³ğŸ‡± VLESS 13
  - ğŸ‡©ğŸ‡ª VLESS 14
  - ğŸ‡©ğŸ‡ª VLESS 15
  - ğŸ‡ºğŸ‡¸ VLESS 16
  - ğŸ‡«ğŸ‡· VLESS 18
  - ğŸ‡³ğŸ‡± VLESS 19
  - ğŸ‡³ğŸ‡± VLESS 20
  - ğŸ‡µğŸ‡± VLESS 21
  - ğŸ‡«ğŸ‡· VLESS 22
  - ğŸ‡ªğŸ‡¸ VLESS 24
  - ğŸ‡³ğŸ‡± VLESS 25
  - ğŸ‡¸ğŸ‡ª VLESS 26
  - ğŸ‡³ğŸ‡± VLESS 28
  - ğŸ‡¬ğŸ‡§ VLESS 32
  - ğŸ‡ºğŸ‡¸ VLESS 33
  - ğŸ‡±ğŸ‡¹ VLESS 35
  - ğŸ‡«ğŸ‡· VLESS 36
  - ğŸ‡³ğŸ‡± VLESS 38
  - ğŸ‡«ğŸ‡· VLESS 39
  - ğŸ‡©ğŸ‡ª VLESS 40
  - ğŸ‡ºğŸ‡¸ VLESS 41
  - ğŸ‡ºğŸ‡¸ TROJAN 42
  - ğŸ‡ºğŸ‡¸ VLESS 43
  - ğŸ‡«ğŸ‡· VLESS 45
  - ğŸ‡¹ğŸ‡· VLESS 46
  - ğŸ‡¬ğŸ‡§ VLESS 47
  - ğŸ‡ºğŸ‡¸ TROJAN 48
  - ğŸ‡«ğŸ‡· VLESS 50
  - ğŸ‡«ğŸ‡· VLESS 54
  - ğŸ‡³ğŸ‡± VLESS 55
  - ğŸ‡«ğŸ‡· VLESS 56
  - ğŸ‡¨ğŸ‡¦ VLESS 58
  - ğŸ‡«ğŸ‡· VLESS 63
  - ğŸ‡«ğŸ‡· VLESS 64
  - ğŸ‡«ğŸ‡· VLESS 65
  - ğŸ‡©ğŸ‡ª VLESS 67
  - ğŸŒ VLESS 68
  - ğŸŒ VLESS 69
- name: Auto
  type: url-test
  icon: https://cdn.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/EU.png
  url: http://gstatic.com/generate_204
  lazy: true
  interval: 120
  tolerance: 200
  hidden: true
  proxies:
  - ğŸ‡©ğŸ‡ª VLESS 01
  - ğŸ‡ºğŸ‡¸ VMESS 02
  - ğŸ‡«ğŸ‡· VLESS 03
  - ğŸ‡ºğŸ‡¸ VLESS 04
  - ğŸ‡¹ğŸ‡· VLESS 05
  - ğŸ‡¹ğŸ‡· VLESS 07
  - ğŸ‡«ğŸ‡· VLESS 08
  - ğŸ‡«ğŸ‡· VLESS 09
  - ğŸ‡©ğŸ‡ª VLESS 10
  - ğŸ‡¬ğŸ‡§ VLESS 12
  - ğŸ‡³ğŸ‡± VLESS 13
  - ğŸ‡©ğŸ‡ª VLESS 14
  - ğŸ‡©ğŸ‡ª VLESS 15
  - ğŸ‡ºğŸ‡¸ VLESS 16
  - ğŸ‡«ğŸ‡· VLESS 18
  - ğŸ‡³ğŸ‡± VLESS 19
  - ğŸ‡³ğŸ‡± VLESS 20
  - ğŸ‡µğŸ‡± VLESS 21
  - ğŸ‡«ğŸ‡· VLESS 22
  - ğŸ‡ªğŸ‡¸ VLESS 24
  - ğŸ‡³ğŸ‡± VLESS 25
  - ğŸ‡¸ğŸ‡ª VLESS 26
  - ğŸ‡³ğŸ‡± VLESS 28
  - ğŸ‡¬ğŸ‡§ VLESS 32
  - ğŸ‡ºğŸ‡¸ VLESS 33
  - ğŸ‡±ğŸ‡¹ VLESS 35
  - ğŸ‡«ğŸ‡· VLESS 36
  - ğŸ‡³ğŸ‡± VLESS 38
  - ğŸ‡«ğŸ‡· VLESS 39
  - ğŸ‡©ğŸ‡ª VLESS 40
  - ğŸ‡ºğŸ‡¸ VLESS 41
  - ğŸ‡ºğŸ‡¸ TROJAN 42
  - ğŸ‡ºğŸ‡¸ VLESS 43
  - ğŸ‡«ğŸ‡· VLESS 45
  - ğŸ‡¹ğŸ‡· VLESS 46
  - ğŸ‡¬ğŸ‡§ VLESS 47
  - ğŸ‡ºğŸ‡¸ TROJAN 48
  - ğŸ‡«ğŸ‡· VLESS 50
  - ğŸ‡«ğŸ‡· VLESS 54
  - ğŸ‡³ğŸ‡± VLESS 55
  - ğŸ‡«ğŸ‡· VLESS 56
  - ğŸ‡¨ğŸ‡¦ VLESS 58
  - ğŸ‡«ğŸ‡· VLESS 63
  - ğŸ‡«ğŸ‡· VLESS 64
  - ğŸ‡«ğŸ‡· VLESS 65
  - ğŸ‡©ğŸ‡ª VLESS 67
  - ğŸŒ VLESS 68
  - ğŸŒ VLESS 69
- name: Load Balancer
  type: load-balance
  strategy: consistent-hashing
  icon: https://cdn.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/Bypass.png
  url: http://gstatic.com/generate_204
  lazy: true
  interval: 120
  tolerance: 200
  hidden: true
  proxies:
  - ğŸ‡©ğŸ‡ª VLESS 01
  - ğŸ‡ºğŸ‡¸ VMESS 02
  - ğŸ‡«ğŸ‡· VLESS 03
  - ğŸ‡ºğŸ‡¸ VLESS 04
  - ğŸ‡¹ğŸ‡· VLESS 05
  - ğŸ‡¹ğŸ‡· VLESS 07
  - ğŸ‡«ğŸ‡· VLESS 08
  - ğŸ‡«ğŸ‡· VLESS 09
  - ğŸ‡©ğŸ‡ª VLESS 10
  - ğŸ‡¬ğŸ‡§ VLESS 12
  - ğŸ‡³ğŸ‡± VLESS 13
  - ğŸ‡©ğŸ‡ª VLESS 14
  - ğŸ‡©ğŸ‡ª VLESS 15
  - ğŸ‡ºğŸ‡¸ VLESS 16
  - ğŸ‡«ğŸ‡· VLESS 18
  - ğŸ‡³ğŸ‡± VLESS 19
  - ğŸ‡³ğŸ‡± VLESS 20
  - ğŸ‡µğŸ‡± VLESS 21
  - ğŸ‡«ğŸ‡· VLESS 22
  - ğŸ‡ªğŸ‡¸ VLESS 24
  - ğŸ‡³ğŸ‡± VLESS 25
  - ğŸ‡¸ğŸ‡ª VLESS 26
  - ğŸ‡³ğŸ‡± VLESS 28
  - ğŸ‡¬ğŸ‡§ VLESS 32
  - ğŸ‡ºğŸ‡¸ VLESS 33
  - ğŸ‡±ğŸ‡¹ VLESS 35
  - ğŸ‡«ğŸ‡· VLESS 36
  - ğŸ‡³ğŸ‡± VLESS 38
  - ğŸ‡«ğŸ‡· VLESS 39
  - ğŸ‡©ğŸ‡ª VLESS 40
  - ğŸ‡ºğŸ‡¸ VLESS 41
  - ğŸ‡ºğŸ‡¸ TROJAN 42
  - ğŸ‡ºğŸ‡¸ VLESS 43
  - ğŸ‡«ğŸ‡· VLESS 45
  - ğŸ‡¹ğŸ‡· VLESS 46
  - ğŸ‡¬ğŸ‡§ VLESS 47
  - ğŸ‡ºğŸ‡¸ TROJAN 48
  - ğŸ‡«ğŸ‡· VLESS 50
  - ğŸ‡«ğŸ‡· VLESS 54
  - ğŸ‡³ğŸ‡± VLESS 55
  - ğŸ‡«ğŸ‡· VLESS 56
  - ğŸ‡¨ğŸ‡¦ VLESS 58
  - ğŸ‡«ğŸ‡· VLESS 63
  - ğŸ‡«ğŸ‡· VLESS 64
  - ğŸ‡«ğŸ‡· VLESS 65
  - ğŸ‡©ğŸ‡ª VLESS 67
  - ğŸŒ VLESS 68
  - ğŸŒ VLESS 69
rule-providers:
  private:
    type: http
    format: text
    behavior: ipcidr
    url: https://github.com/Chocolate4U/Iran-clash-rules/releases/latest/download/private.txt
    path: ./ruleset/private.txt
    interval: 86400
  ircidr:
    type: http
    format: text
    behavior: ipcidr
    url: https://github.com/Chocolate4U/Iran-clash-rules/releases/latest/download/ircidr.txt
    path: ./ruleset/ircidr.txt
    interval: 86400
  iran_other:
    type: http
    format: text
    behavior: domain
    url: https://github.com/bootmortis/iran-hosted-domains/releases/latest/download/clash_rules_other.txt
    path: ./ruleset/iran_other.txt
    interval: 86400
  apps:
    type: http
    format: text
    behavior: classical
    url: https://github.com/Chocolate4U/Iran-clash-rules/releases/latest/download/apps.txt
    path: ./ruleset/apps.txt
    interval: 86400
  Pro:
    type: http
    format: text
    behavior: domain
    url: https://github.com/Chocolate4U/Iran-clash-rules/releases/latest/download/nsfw.txt
    path: ./ruleset/pro.txt
    interval: 86400
  ads:
    type: http
    format: text
    behavior: domain
    url: https://github.com/Chocolate4U/Iran-clash-rules/releases/latest/download/category-ads-all.txt
    path: ./ruleset/ads.txt
    interval: 86400
  malware:
    type: http
    format: text
    behavior: domain
    url: https://github.com/Chocolate4U/Iran-clash-rules/releases/latest/download/malware.txt
    path: ./ruleset/malware.txt
    interval: 86400
  phishing:
    type: http
    format: text
    behavior: domain
    url: https://github.com/Chocolate4U/Iran-clash-rules/releases/latest/download/phishing.txt
    path: ./ruleset/phishing.txt
    interval: 86400
  cryptominers:
    type: http
    format: text
    behavior: domain
    url: https://github.com/Chocolate4U/Iran-clash-rules/releases/latest/download/cryptominers.txt
    path: ./ruleset/cryptominers.txt
    interval: 86400
  malware-ip:
    type: http
    format: text
    behavior: ipcidr
    url: https://github.com/Chocolate4U/Iran-clash-rules/releases/latest/download/malware-ip.txt
    path: ./ruleset/malware-ip.txt
    interval: 86400
  phishing-ip:
    type: http
    format: text
    behavior: ipcidr
    url: https://github.com/Chocolate4U/Iran-clash-rules/releases/latest/download/phishing-ip.txt
    path: ./ruleset/phishing-ip.txt
    interval: 86400
rules:
- DOMAIN-SUFFIX,ir,DIRECT
- DOMAIN-SUFFIX,.ir,DIRECT
- DOMAIN,www.cloudflare.com,DIRECT
- RULE-SET,ads,REJECT
- RULE-SET,malware,REJECT
- RULE-SET,malware-ip,REJECT
- RULE-SET,phishing,REJECT
- RULE-SET,phishing-ip,REJECT
- RULE-SET,cryptominers,REJECT
- RULE-SET,private,DIRECT
- RULE-SET,ircidr,DIRECT
- RULE-SET,iran_other,DIRECT
- RULE-SET,apps,DIRECT
- MATCH,Smart VPN
ntp:
  enable: true
  server: time.apple.com
  port: 123
  interval: 30
