mixed-port: 7890
ipv6: false
allow-lan: true
mode: rule
log-level: silent
geo-auto-update: true
geo-update-interval: 168
enable-process: true
find-process-mode: strict
tcp-concurrent: true
profile:
  store-selected: true
  store-fake-ip: true
sniffer:
  enable: true
  parse-pure-ip: true
  force-dns-mapping: true
  override-destination: false
dns:
  enable: true
  listen: 0.0.0.0:1053
  ipv6: false
  respect-rules: true
  use-system-hosts: false
  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.1/16
  fake-ip-filter-mode: blacklist
  fake-ip-filter:
  - rule-set:private
  default-nameserver:
  - 8.8.8.8
  - 8.8.4.4
  nameserver:
  - 4.2.2.4
  - 1.1.1.1
  direct-nameserver:
  - 8.8.8.8
  - 8.8.4.4
  proxy-server-nameserver:
  - 4.2.2.4
  - 1.1.1.1
  fallback:
  - quic://8.8.8.8
  - quic://8.8.4.4
  - https://google.com/dns-query
  - https://8.8.8.8/dns-query
  fallback-filter:
    ipcidr:
    - 10.10.34.34/29
tun:
  enable: true
  stack: gvisor
  auto-route: true
  auto-redirect: true
  strict-route: true
  dns-hijack:
  - any:53
  - tcp://any:53
proxies:
- name: ğŸ‡©ğŸ‡ª VLESS 01
  type: vless
  server: 212.95.34.22
  port: 443
  uuid: 784646e5-8e84-4672-8670-efc9cafcd2cc
  udp: true
  tls: true
  skip-cert-verify: true
  servername: 212.95.34.22
  network: ws
  ws-opts:
    path: /
- name: ğŸ‡©ğŸ‡ª VLESS 02
  type: vless
  server: 212.95.34.28
  port: 443
  uuid: 784646e5-8e84-4672-8670-efc9cafcd2cc
  udp: true
  tls: true
  skip-cert-verify: true
  servername: 212.95.34.28
  network: ws
  ws-opts:
    path: /
- name: ğŸ‡©ğŸ‡ª VLESS 04
  type: vless
  server: 212.95.34.21
  port: 443
  uuid: 784646e5-8e84-4672-8670-efc9cafcd2cc
  udp: true
  tls: true
  skip-cert-verify: true
  servername: 212.95.34.21
  network: ws
  ws-opts:
    path: /
- name: ğŸ‡©ğŸ‡ª VLESS 05
  type: vless
  server: 212.95.34.9
  port: 443
  uuid: 784646e5-8e84-4672-8670-efc9cafcd2cc
  udp: true
  tls: true
  skip-cert-verify: true
  servername: 212.95.34.9
  network: ws
  ws-opts:
    path: /
- name: ğŸ‡©ğŸ‡ª VLESS 07
  type: vless
  server: 212.95.34.20
  port: 443
  uuid: 784646e5-8e84-4672-8670-efc9cafcd2cc
  udp: true
  tls: true
  skip-cert-verify: true
  servername: 212.95.34.20
  network: ws
  ws-opts:
    path: /
- name: ğŸ‡¸ğŸ‡¬ VLESS 09
  type: vless
  server: ipw.gfdv54cvghhgfhgj-njhgj64.info
  port: 443
  uuid: 337bf72e-bb79-4d5f-be3f-7822eb77100c
  udp: true
  tls: true
  skip-cert-verify: true
  servername: 9Mp6PkM999.aDcFv.InFo
  network: ws
  client-fingerprint: chrome
  ws-opts:
    path: /
    headers:
      Host: 9Mp6PkM999.aDcFv.InFo
- name: ğŸ‡ºğŸ‡¸ VLESS 10
  type: vless
  server: 185.236.232.148
  port: 8880
  uuid: e4824193-4f54-453b-d037-88368e85ef0e
  udp: true
  tls: false
  skip-cert-verify: true
  servername: 185.236.232.148
  network: grpc
  grpc-opts: {}
- name: ğŸ‡ºğŸ‡¸ VLESS 11
  type: vless
  server: 185.236.232.116
  port: 8880
  uuid: e4824193-4f54-453b-d037-88368e85ef0e
  udp: true
  tls: false
  skip-cert-verify: true
  servername: 185.236.232.116
  network: grpc
  grpc-opts: {}
- name: ğŸ‡ºğŸ‡¸ VLESS 12
  type: vless
  server: 185.236.232.157
  port: 8880
  uuid: e4824193-4f54-453b-d037-88368e85ef0e
  udp: true
  tls: false
  skip-cert-verify: true
  servername: 185.236.232.157
  network: grpc
  grpc-opts: {}
- name: ğŸ‡¯ğŸ‡µ VLESS 13
  type: vless
  server: amazon-15.cristiano.name.ng
  port: 443
  uuid: 4c26ebc3-7784-46d8-b52a-7b0ccae6f4b4
  udp: true
  tls: true
  skip-cert-verify: true
  servername: store.steampowered.com
  network: tcp
  client-fingerprint: chrome
  flow: xtls-rprx-vision
  reality-opts:
    public-key: TGlPtfVzGIVpMauPRMGJj2Uu6GUiCpu5ZizIIjw-wx4
    short-id: f5
- name: ğŸ‡ºğŸ‡¸ VLESS 14
  type: vless
  server: 45.86.72.106
  port: 8880
  uuid: e4824193-4f54-453b-d037-88368e85ef0e
  udp: true
  tls: false
  skip-cert-verify: true
  servername: 45.86.72.106
  network: grpc
  grpc-opts: {}
- name: ğŸ‡¨ğŸ‡¦ VLESS 15
  type: vless
  server: www.speedtest.net
  port: 8443
  uuid: ccbe6b7c-9264-40c4-8bc1-ef8f6205d7a4
  udp: true
  tls: true
  skip-cert-verify: true
  servername: hetzner-13.bibar.name.ng
  network: ws
  ws-opts:
    path: /
    headers:
      Host: hetzner-13.bibar.name.ng
- name: ğŸ‡¨ğŸ‡¦ VLESS 16
  type: vless
  server: www.speedtest.net
  port: 2095
  uuid: abd510b1-881c-4360-c633-84e1024c1386
  udp: true
  tls: false
  skip-cert-verify: true
  servername: www.speedtest.net
  network: tcp
- name: ğŸ‡¬ğŸ‡§ VLESS 17
  type: vless
  server: 51.195.202.129
  port: 443
  uuid: a00b3f51-36ec-4960-9668-a30ad2f68421
  udp: true
  tls: true
  skip-cert-verify: true
  servername: zula.ir
  network: ws
  client-fingerprint: chrome
  ws-opts:
    path: /ws
- name: ğŸ‡¨ğŸ‡¦ VLESS 18
  type: vless
  server: 148.113.207.224
  port: 443
  uuid: 74d03a21-f000-4b08-9dd8-440f0e4d6622
  udp: true
  tls: true
  skip-cert-verify: true
  servername: zula.ir
  network: ws
  client-fingerprint: chrome
  ws-opts:
    path: /ws
- name: ğŸ‡«ğŸ‡· VLESS 19
  type: vless
  server: 51.178.42.187
  port: 443
  uuid: ff288332-d2d2-473d-9b30-b6ab97f27b90
  udp: true
  tls: true
  skip-cert-verify: true
  servername: zula.ir
  network: ws
  client-fingerprint: chrome
  ws-opts:
    path: /ws
- name: ğŸ‡µğŸ‡± VLESS 20
  type: vless
  server: 57.128.219.105
  port: 443
  uuid: cf0b2cdc-9292-450d-929a-af86ed52d87d
  udp: true
  tls: true
  skip-cert-verify: true
  servername: zula.ir
  network: ws
  client-fingerprint: chrome
  ws-opts:
    path: /ws
- name: ğŸ‡©ğŸ‡ª VLESS 21
  type: vless
  server: 51.195.101.222
  port: 443
  uuid: 29f55cea-4038-402c-a496-2e8ae2d8e660
  udp: true
  tls: true
  skip-cert-verify: true
  servername: zula.ir
  network: ws
  client-fingerprint: chrome
  ws-opts:
    path: /ws
- name: ğŸ‡©ğŸ‡ª VLESS 22
  type: vless
  server: 212.95.34.15
  port: 443
  uuid: 784646e5-8e84-4672-8670-efc9cafcd2cc
  udp: true
  tls: true
  skip-cert-verify: true
  servername: 212.95.34.15
  network: ws
  ws-opts:
    path: /
- name: ğŸ‡©ğŸ‡ª VLESS 23
  type: vless
  server: 159.65.119.239
  port: 443
  uuid: 1e1858cd-def6-4408-a9d2-153d1f2fe47e
  udp: true
  tls: true
  skip-cert-verify: true
  servername: zula.ir
  network: ws
  client-fingerprint: chrome
  ws-opts:
    path: /ws
- name: ğŸ‡«ğŸ‡® VMESS 24
  type: vmess
  server: 135.181.102.63
  port: 2082
  uuid: 24682dda-4318-4ce3-b373-f6b729113f12
  alterId: 0
  udp: true
  skip-cert-verify: true
  cipher: auto
  network: ws
  ws-opts:
    path: 24682dda-4318-4ce3-b373-f6b729113f12-vm
    headers:
      Host: www.bing.com
- name: ğŸ‡©ğŸ‡ª VLESS 25
  type: vless
  server: 212.95.34.11
  port: 443
  uuid: 784646e5-8e84-4672-8670-efc9cafcd2cc
  udp: true
  tls: true
  skip-cert-verify: true
  servername: 212.95.34.11
  network: ws
  ws-opts:
    path: /
- name: ğŸ‡©ğŸ‡ª VLESS 26
  type: vless
  server: 212.95.34.14
  port: 443
  uuid: 784646e5-8e84-4672-8670-efc9cafcd2cc
  udp: true
  tls: true
  skip-cert-verify: true
  servername: 212.95.34.14
  network: ws
  ws-opts:
    path: /
- name: ğŸ‡©ğŸ‡ª VLESS 27
  type: vless
  server: 212.95.34.16
  port: 443
  uuid: 784646e5-8e84-4672-8670-efc9cafcd2cc
  udp: true
  tls: true
  skip-cert-verify: true
  servername: 212.95.34.16
  network: ws
  ws-opts:
    path: /
- name: ğŸ‡«ğŸ‡· VMESS 30
  type: vmess
  server: 38.60.134.249
  port: 443
  uuid: beb28159-7f4c-4c09-9313-6283515f150b
  alterId: 0
  udp: true
  skip-cert-verify: true
  cipher: none
  network: tcp
- name: ğŸ‡®ğŸ‡¶ VMESS 31
  type: vmess
  server: 154.93.37.21
  port: 443
  uuid: 64a37ce5-e713-4ad4-c1de-b68761e9fef6
  alterId: 0
  udp: true
  skip-cert-verify: true
  cipher: none
  network: tcp
- name: ğŸ‡©ğŸ‡ª VLESS 33
  type: vless
  server: 212.95.34.24
  port: 443
  uuid: 784646e5-8e84-4672-8670-efc9cafcd2cc
  udp: true
  tls: true
  skip-cert-verify: true
  servername: 212.95.34.24
  network: ws
  ws-opts:
    path: /
- name: ğŸ‡¨ğŸ‡¦ VLESS 34
  type: vless
  server: 51.79.29.172
  port: 33801
  uuid: 13c10b21-6211-4d43-856f-2e54ef2ac2e2
  udp: true
  tls: false
  skip-cert-verify: true
  servername: 51.79.29.172
  network: tcp
- name: ğŸ‡©ğŸ‡ª VLESS 38
  type: vless
  server: 212.95.34.17
  port: 443
  uuid: 784646e5-8e84-4672-8670-efc9cafcd2cc
  udp: true
  tls: true
  skip-cert-verify: true
  servername: 212.95.34.17
  network: ws
  ws-opts:
    path: /
- name: ğŸ‡©ğŸ‡ª VLESS 40
  type: vless
  server: 212.95.34.30
  port: 443
  uuid: 784646e5-8e84-4672-8670-efc9cafcd2cc
  udp: true
  tls: true
  skip-cert-verify: true
  servername: 212.95.34.30
  network: ws
  ws-opts:
    path: /
- name: ğŸ‡©ğŸ‡ª VLESS 42
  type: vless
  server: 212.95.34.4
  port: 443
  uuid: 784646e5-8e84-4672-8670-efc9cafcd2cc
  udp: true
  tls: true
  skip-cert-verify: true
  servername: 212.95.34.4
  network: ws
  ws-opts:
    path: /
- name: ğŸ‡©ğŸ‡ª VLESS 43
  type: vless
  server: 212.95.34.6
  port: 443
  uuid: 784646e5-8e84-4672-8670-efc9cafcd2cc
  udp: true
  tls: true
  skip-cert-verify: true
  servername: 212.95.34.6
  network: ws
  ws-opts:
    path: /
- name: ğŸ‡©ğŸ‡ª VLESS 44
  type: vless
  server: 212.95.34.8
  port: 443
  uuid: 784646e5-8e84-4672-8670-efc9cafcd2cc
  udp: true
  tls: true
  skip-cert-verify: true
  servername: 212.95.34.8
  network: ws
  ws-opts:
    path: /
- name: ğŸ‡©ğŸ‡ª VLESS 46
  type: vless
  server: 212.95.34.10
  port: 443
  uuid: 784646e5-8e84-4672-8670-efc9cafcd2cc
  udp: true
  tls: true
  skip-cert-verify: true
  servername: 212.95.34.10
  network: ws
  ws-opts:
    path: /
- name: ğŸ‡©ğŸ‡ª VLESS 47
  type: vless
  server: 212.95.34.12
  port: 443
  uuid: 784646e5-8e84-4672-8670-efc9cafcd2cc
  udp: true
  tls: true
  skip-cert-verify: true
  servername: 212.95.34.12
  network: ws
  ws-opts:
    path: /
- name: ğŸ‡©ğŸ‡ª VLESS 48
  type: vless
  server: 212.95.34.13
  port: 443
  uuid: 784646e5-8e84-4672-8670-efc9cafcd2cc
  udp: true
  tls: true
  skip-cert-verify: true
  servername: 212.95.34.13
  network: ws
  ws-opts:
    path: /
- name: ğŸ‡©ğŸ‡ª VLESS 52
  type: vless
  server: 212.95.34.18
  port: 443
  uuid: 784646e5-8e84-4672-8670-efc9cafcd2cc
  udp: true
  tls: true
  skip-cert-verify: true
  servername: 212.95.34.18
  network: ws
  ws-opts:
    path: /
- name: ğŸ‡©ğŸ‡ª VLESS 53
  type: vless
  server: 212.95.34.19
  port: 443
  uuid: 784646e5-8e84-4672-8670-efc9cafcd2cc
  udp: true
  tls: true
  skip-cert-verify: true
  servername: 212.95.34.19
  network: ws
  ws-opts:
    path: /
- name: ğŸ‡©ğŸ‡ª VLESS 56
  type: vless
  server: 212.95.34.25
  port: 443
  uuid: 784646e5-8e84-4672-8670-efc9cafcd2cc
  udp: true
  tls: true
  skip-cert-verify: true
  servername: 212.95.34.25
  network: ws
  ws-opts:
    path: /
- name: ğŸ‡©ğŸ‡ª VLESS 57
  type: vless
  server: 212.95.34.26
  port: 443
  uuid: 784646e5-8e84-4672-8670-efc9cafcd2cc
  udp: true
  tls: true
  skip-cert-verify: true
  servername: 212.95.34.26
  network: ws
  ws-opts:
    path: /
- name: ğŸ‡©ğŸ‡ª VLESS 58
  type: vless
  server: 212.95.34.29
  port: 443
  uuid: 784646e5-8e84-4672-8670-efc9cafcd2cc
  udp: true
  tls: true
  skip-cert-verify: true
  servername: 212.95.34.29
  network: ws
  ws-opts:
    path: /
- name: ğŸ‡©ğŸ‡ª VLESS 59
  type: vless
  server: 212.95.34.31
  port: 443
  uuid: 784646e5-8e84-4672-8670-efc9cafcd2cc
  udp: true
  tls: true
  skip-cert-verify: true
  servername: 212.95.34.31
  network: ws
  ws-opts:
    path: /
- name: ğŸ‡©ğŸ‡ª VLESS 60
  type: vless
  server: 212.95.34.32
  port: 443
  uuid: 784646e5-8e84-4672-8670-efc9cafcd2cc
  udp: true
  tls: true
  skip-cert-verify: true
  servername: 212.95.34.32
  network: ws
  ws-opts:
    path: /
proxy-groups:
- name: Smart VPN
  type: select
  lazy: true
  icon: https://cdn.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/Global.png
  proxies:
  - Auto
  - Load Balancer
  - ğŸ‡©ğŸ‡ª VLESS 01
  - ğŸ‡©ğŸ‡ª VLESS 02
  - ğŸ‡©ğŸ‡ª VLESS 04
  - ğŸ‡©ğŸ‡ª VLESS 05
  - ğŸ‡©ğŸ‡ª VLESS 07
  - ğŸ‡¸ğŸ‡¬ VLESS 09
  - ğŸ‡ºğŸ‡¸ VLESS 10
  - ğŸ‡ºğŸ‡¸ VLESS 11
  - ğŸ‡ºğŸ‡¸ VLESS 12
  - ğŸ‡¯ğŸ‡µ VLESS 13
  - ğŸ‡ºğŸ‡¸ VLESS 14
  - ğŸ‡¨ğŸ‡¦ VLESS 15
  - ğŸ‡¨ğŸ‡¦ VLESS 16
  - ğŸ‡¬ğŸ‡§ VLESS 17
  - ğŸ‡¨ğŸ‡¦ VLESS 18
  - ğŸ‡«ğŸ‡· VLESS 19
  - ğŸ‡µğŸ‡± VLESS 20
  - ğŸ‡©ğŸ‡ª VLESS 21
  - ğŸ‡©ğŸ‡ª VLESS 22
  - ğŸ‡©ğŸ‡ª VLESS 23
  - ğŸ‡«ğŸ‡® VMESS 24
  - ğŸ‡©ğŸ‡ª VLESS 25
  - ğŸ‡©ğŸ‡ª VLESS 26
  - ğŸ‡©ğŸ‡ª VLESS 27
  - ğŸ‡«ğŸ‡· VMESS 30
  - ğŸ‡®ğŸ‡¶ VMESS 31
  - ğŸ‡©ğŸ‡ª VLESS 33
  - ğŸ‡¨ğŸ‡¦ VLESS 34
  - ğŸ‡©ğŸ‡ª VLESS 38
  - ğŸ‡©ğŸ‡ª VLESS 40
  - ğŸ‡©ğŸ‡ª VLESS 42
  - ğŸ‡©ğŸ‡ª VLESS 43
  - ğŸ‡©ğŸ‡ª VLESS 44
  - ğŸ‡©ğŸ‡ª VLESS 46
  - ğŸ‡©ğŸ‡ª VLESS 47
  - ğŸ‡©ğŸ‡ª VLESS 48
  - ğŸ‡©ğŸ‡ª VLESS 52
  - ğŸ‡©ğŸ‡ª VLESS 53
  - ğŸ‡©ğŸ‡ª VLESS 56
  - ğŸ‡©ğŸ‡ª VLESS 57
  - ğŸ‡©ğŸ‡ª VLESS 58
  - ğŸ‡©ğŸ‡ª VLESS 59
  - ğŸ‡©ğŸ‡ª VLESS 60
- name: Auto
  type: url-test
  icon: https://cdn.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/EU.png
  url: http://gstatic.com/generate_204
  lazy: true
  interval: 120
  tolerance: 200
  hidden: true
  proxies:
  - ğŸ‡©ğŸ‡ª VLESS 01
  - ğŸ‡©ğŸ‡ª VLESS 02
  - ğŸ‡©ğŸ‡ª VLESS 04
  - ğŸ‡©ğŸ‡ª VLESS 05
  - ğŸ‡©ğŸ‡ª VLESS 07
  - ğŸ‡¸ğŸ‡¬ VLESS 09
  - ğŸ‡ºğŸ‡¸ VLESS 10
  - ğŸ‡ºğŸ‡¸ VLESS 11
  - ğŸ‡ºğŸ‡¸ VLESS 12
  - ğŸ‡¯ğŸ‡µ VLESS 13
  - ğŸ‡ºğŸ‡¸ VLESS 14
  - ğŸ‡¨ğŸ‡¦ VLESS 15
  - ğŸ‡¨ğŸ‡¦ VLESS 16
  - ğŸ‡¬ğŸ‡§ VLESS 17
  - ğŸ‡¨ğŸ‡¦ VLESS 18
  - ğŸ‡«ğŸ‡· VLESS 19
  - ğŸ‡µğŸ‡± VLESS 20
  - ğŸ‡©ğŸ‡ª VLESS 21
  - ğŸ‡©ğŸ‡ª VLESS 22
  - ğŸ‡©ğŸ‡ª VLESS 23
  - ğŸ‡«ğŸ‡® VMESS 24
  - ğŸ‡©ğŸ‡ª VLESS 25
  - ğŸ‡©ğŸ‡ª VLESS 26
  - ğŸ‡©ğŸ‡ª VLESS 27
  - ğŸ‡«ğŸ‡· VMESS 30
  - ğŸ‡®ğŸ‡¶ VMESS 31
  - ğŸ‡©ğŸ‡ª VLESS 33
  - ğŸ‡¨ğŸ‡¦ VLESS 34
  - ğŸ‡©ğŸ‡ª VLESS 38
  - ğŸ‡©ğŸ‡ª VLESS 40
  - ğŸ‡©ğŸ‡ª VLESS 42
  - ğŸ‡©ğŸ‡ª VLESS 43
  - ğŸ‡©ğŸ‡ª VLESS 44
  - ğŸ‡©ğŸ‡ª VLESS 46
  - ğŸ‡©ğŸ‡ª VLESS 47
  - ğŸ‡©ğŸ‡ª VLESS 48
  - ğŸ‡©ğŸ‡ª VLESS 52
  - ğŸ‡©ğŸ‡ª VLESS 53
  - ğŸ‡©ğŸ‡ª VLESS 56
  - ğŸ‡©ğŸ‡ª VLESS 57
  - ğŸ‡©ğŸ‡ª VLESS 58
  - ğŸ‡©ğŸ‡ª VLESS 59
  - ğŸ‡©ğŸ‡ª VLESS 60
- name: Load Balancer
  type: load-balance
  strategy: consistent-hashing
  icon: https://cdn.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/Bypass.png
  url: http://gstatic.com/generate_204
  lazy: true
  interval: 120
  tolerance: 200
  hidden: true
  proxies:
  - ğŸ‡©ğŸ‡ª VLESS 01
  - ğŸ‡©ğŸ‡ª VLESS 02
  - ğŸ‡©ğŸ‡ª VLESS 04
  - ğŸ‡©ğŸ‡ª VLESS 05
  - ğŸ‡©ğŸ‡ª VLESS 07
  - ğŸ‡¸ğŸ‡¬ VLESS 09
  - ğŸ‡ºğŸ‡¸ VLESS 10
  - ğŸ‡ºğŸ‡¸ VLESS 11
  - ğŸ‡ºğŸ‡¸ VLESS 12
  - ğŸ‡¯ğŸ‡µ VLESS 13
  - ğŸ‡ºğŸ‡¸ VLESS 14
  - ğŸ‡¨ğŸ‡¦ VLESS 15
  - ğŸ‡¨ğŸ‡¦ VLESS 16
  - ğŸ‡¬ğŸ‡§ VLESS 17
  - ğŸ‡¨ğŸ‡¦ VLESS 18
  - ğŸ‡«ğŸ‡· VLESS 19
  - ğŸ‡µğŸ‡± VLESS 20
  - ğŸ‡©ğŸ‡ª VLESS 21
  - ğŸ‡©ğŸ‡ª VLESS 22
  - ğŸ‡©ğŸ‡ª VLESS 23
  - ğŸ‡«ğŸ‡® VMESS 24
  - ğŸ‡©ğŸ‡ª VLESS 25
  - ğŸ‡©ğŸ‡ª VLESS 26
  - ğŸ‡©ğŸ‡ª VLESS 27
  - ğŸ‡«ğŸ‡· VMESS 30
  - ğŸ‡®ğŸ‡¶ VMESS 31
  - ğŸ‡©ğŸ‡ª VLESS 33
  - ğŸ‡¨ğŸ‡¦ VLESS 34
  - ğŸ‡©ğŸ‡ª VLESS 38
  - ğŸ‡©ğŸ‡ª VLESS 40
  - ğŸ‡©ğŸ‡ª VLESS 42
  - ğŸ‡©ğŸ‡ª VLESS 43
  - ğŸ‡©ğŸ‡ª VLESS 44
  - ğŸ‡©ğŸ‡ª VLESS 46
  - ğŸ‡©ğŸ‡ª VLESS 47
  - ğŸ‡©ğŸ‡ª VLESS 48
  - ğŸ‡©ğŸ‡ª VLESS 52
  - ğŸ‡©ğŸ‡ª VLESS 53
  - ğŸ‡©ğŸ‡ª VLESS 56
  - ğŸ‡©ğŸ‡ª VLESS 57
  - ğŸ‡©ğŸ‡ª VLESS 58
  - ğŸ‡©ğŸ‡ª VLESS 59
  - ğŸ‡©ğŸ‡ª VLESS 60
rule-providers:
  private:
    type: http
    format: text
    behavior: ipcidr
    url: https://github.com/Chocolate4U/Iran-clash-rules/releases/latest/download/private.txt
    path: ./ruleset/private.txt
    interval: 86400
  ircidr:
    type: http
    format: text
    behavior: ipcidr
    url: https://github.com/Chocolate4U/Iran-clash-rules/releases/latest/download/ircidr.txt
    path: ./ruleset/ircidr.txt
    interval: 86400
  iran_other:
    type: http
    format: text
    behavior: domain
    url: https://github.com/bootmortis/iran-hosted-domains/releases/latest/download/clash_rules_other.txt
    path: ./ruleset/iran_other.txt
    interval: 86400
  apps:
    type: http
    format: text
    behavior: classical
    url: https://github.com/Chocolate4U/Iran-clash-rules/releases/latest/download/apps.txt
    path: ./ruleset/apps.txt
    interval: 86400
  Pro:
    type: http
    format: text
    behavior: domain
    url: https://github.com/Chocolate4U/Iran-clash-rules/releases/latest/download/nsfw.txt
    path: ./ruleset/pro.txt
    interval: 86400
  ads:
    type: http
    format: text
    behavior: domain
    url: https://github.com/Chocolate4U/Iran-clash-rules/releases/latest/download/category-ads-all.txt
    path: ./ruleset/ads.txt
    interval: 86400
  malware:
    type: http
    format: text
    behavior: domain
    url: https://github.com/Chocolate4U/Iran-clash-rules/releases/latest/download/malware.txt
    path: ./ruleset/malware.txt
    interval: 86400
  phishing:
    type: http
    format: text
    behavior: domain
    url: https://github.com/Chocolate4U/Iran-clash-rules/releases/latest/download/phishing.txt
    path: ./ruleset/phishing.txt
    interval: 86400
  cryptominers:
    type: http
    format: text
    behavior: domain
    url: https://github.com/Chocolate4U/Iran-clash-rules/releases/latest/download/cryptominers.txt
    path: ./ruleset/cryptominers.txt
    interval: 86400
  malware-ip:
    type: http
    format: text
    behavior: ipcidr
    url: https://github.com/Chocolate4U/Iran-clash-rules/releases/latest/download/malware-ip.txt
    path: ./ruleset/malware-ip.txt
    interval: 86400
  phishing-ip:
    type: http
    format: text
    behavior: ipcidr
    url: https://github.com/Chocolate4U/Iran-clash-rules/releases/latest/download/phishing-ip.txt
    path: ./ruleset/phishing-ip.txt
    interval: 86400
rules:
- DOMAIN-SUFFIX,ir,DIRECT
- DOMAIN-SUFFIX,.ir,DIRECT
- DOMAIN,www.cloudflare.com,DIRECT
- RULE-SET,ads,REJECT
- RULE-SET,malware,REJECT
- RULE-SET,malware-ip,REJECT
- RULE-SET,phishing,REJECT
- RULE-SET,phishing-ip,REJECT
- RULE-SET,cryptominers,REJECT
- RULE-SET,private,DIRECT
- RULE-SET,ircidr,DIRECT
- RULE-SET,iran_other,DIRECT
- RULE-SET,apps,DIRECT
- MATCH,Smart VPN
ntp:
  enable: true
  server: time.apple.com
  port: 123
  interval: 30
